### ISSUE TITLE
Refactor MetaStore setup to load data from github or local files from script etc

### ISSUE THREAD

**Issue by rufuspollock** [datopian/gift-portal#38]
Now we have done #31 and have an approach for global data we want to use that. Approach:

* `data/catalog.json` has a list of datasets in the catalog (github urls)
* `data/metastore.json` <- built file containing the metastore data as an array of datasets

## Acceptance

* [ ] `data/catalog.json` exists with an array of github urls ((?) and/or local file paths). These are what script uses to run at build ...
* [ ] Data from github (or fixtures) gets loaded into `data/metastore.json` by a script at build time
* [ ] MetaStore loads data from `data/metastore.json` similar to current setup of loading from db

**Comment by steveoni** [comment]
To be clear; i think the reason for this issue is to prevent the need for fetching data from github per-request; if so, the current implementation of `gift-portal` deployed does not fetch data from github per request, every data is fetched at built time, even data needed for the dynamic pages `[datasetid].js` are readily available.

And also I added the ability to update the data automatically per week, in case there is new GitHub data.

cc: @rufuspollock

**Comment by sglavoie** [comment]
Based on today's discussion with @steveoni and @rufuspollock, we are moving this to **Someday Maybe**.

**Comment by risenW** [comment]
Closing this since we implemented Metastore in #75
